version: '3.2'

services:
  elasticsearch:
    container_name: elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    image: elasticsearch:${SENZING_DOCKER_IMAGE_VERSION_ELASTICSEARCH:-latest}

    networks:
      - elk
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elk/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
      - elasticsearch:/usr/share/elasticsearch/data:z

  logstash:
    container_name: logstash
    depends_on:
      - elasticsearch
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    image: logstash:${SENZING_DOCKER_IMAGE_VERSION_LOGSTASH:-latest}
    networks:
      - elk
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    volumes:
      - ./elk/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,z
      - ./elk/logstash/pipeline:/usr/share/logstash/pipeline:ro,z

  kibana:
    container_name: kibana
    depends_on:
      - elasticsearch
    image: kibana:${SENZING_DOCKER_IMAGE_VERSION_KIBANA:-latest}
    networks:
      - elk
    ports:
      - "5601:5601"
    volumes:
      - ./elk/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,z

  logspout:
    container_name: logspout
    depends_on:
       - elasticsearch
       - logstash
       - kibana
    environment:
      ROUTE_URIS: logstash+tcp://logstash:5000
#   image: gliderlabs/logspout:v3.2.14
    image: senzing/logspout-logstash
    networks:
      - elk
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  rabbitmq:
    container_name: senzing-rabbitmq
    depends_on:
      - kibana
    environment:
#     See https://github.com/bitnami/bitnami-docker-rabbitmq#configuration
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-bitnami}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME:-user}
    image: bitnami/rabbitmq:${SENZING_DOCKER_IMAGE_VERSION_BITNAMI_RABBITMQ:-3.8.19-debian-10-r6}
#   logging:
#     driver: gelf
#     options:
#       gelf-address: "udp://localhost:12201"
#       tag: "senzing-rabbitmq"
    networks:
      - elk
    ports:
      - 15672:15672
      - 5672:5672
    restart: always
    volumes:
      - ${RABBITMQ_DIR}:/bitnami

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
