version: '3'
services:

  elasticsearch:
    container_name: senzing-elasticsearch
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      xpack.security.enabled: 'false'
    image: elasticsearch:${SENZING_DOCKER_IMAGE_VERSION_ELASTICSEARCH:-latest}
    networks:
      - senzing
    ports:
      - 9200:9200
      - 9300:9300
    restart: always
 
  logstash:
    command:
      - --config.string
      - >-
        input {
          gelf {
            port => 12201
          }
        }
        output {
          elasticsearch {
            hosts => ["http://elasticsearch:9200"]
            index => "logstash-%{+YYYY-MM-dd}"
          }
        }
    container_name: senzing-logstash
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    image: logstash:${SENZING_DOCKER_IMAGE_VERSION_LOGSTASH:-latest}
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "senzing-logstash"
    networks:
      - senzing
    ports:
      - 9600:9600
      - 12201:12201/udp
    restart: always
    
  kibana:
    container_name: senzing-kibana
    depends_on:
      - elasticsearch
      - logstash
    image: kibana:${SENZING_DOCKER_IMAGE_VERSION_KIBANA:-latest}
    networks:
      - senzing
    ports:
      - 5601:5601
    restart: always
    
networks:
  senzing:
    name: ${SENZING_DOCKER_NETWORK:-senzing-network}
