version: '3'
services:

  webapp:
    container_name: senzing-webapp
    environment:
#     See https://github.com/Senzing/entity-search-web-app#configuration
      SENZING_API_SERVER_URL: ${SENZING_API_SERVER_URL}
      SENZING_WEB_SERVER_ADMIN_AUTH_MODE: JWT
      SENZING_WEB_SERVER_ADMIN_AUTH_PATH: ${SENZING_WEB_SERVER_ADMIN_AUTH_PATH}
      SENZING_WEB_SERVER_API_PATH: /api
      SENZING_WEB_SERVER_PORT: 8251
      SENZING_WEB_SERVER_URL: ${SENZING_WEB_SERVER_URL}
    image: senzing/entity-search-web-app:${SENZING_DOCKER_IMAGE_VERSION_ENTITY_SEARCH_WEB_APP:-latest}
    networks:
      - backend
    ports:
      - 8251:8251
    restart: always

networks:
  backend:
