name: add to project garage

on:
  issues:
    types:
      - opened
      - reopened

jobs:
  add-to-project:
    name: add issue to project
    runs-on: ubuntu-latest

    steps:
      - name: assign issue to project
        uses: actions/add-to-project@v0.6.1
        with:
          github-token: ${{ secrets.SENZING_GITHUB_ACCESS_TOKEN }}
          project-url: https://github.com/orgs/${{ vars.SENZING_GITHUB_ACCOUNT_NAME }}/projects/${{ vars.SENZING_PROJECT_GARAGE }}
