name: add-label-triage.yaml
on:
  issues:
    types:
      - reopened
      - opened
jobs:
  automate-issues-labels:
    name: Add triage label to issue
    runs-on: ubuntu-latest
    steps:
      - name: Add triage label
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: "triage"
