name: add-to-project-garage.yaml
on:
  issues:
    types:
      - reopened
      - opened
jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - name: Assign issue to project
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/senzing-garage/projects/3
          github-token: ${{ secrets.SENZING_GITHUB_ACCESS_TOKEN }}
